kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all
spec:
  podSelector:
    matchLabels:
      app: insights-admission
  egress: # TODO: this only really needs insights.fairwinds.com, but need to configure for self-hosted
  - {}
  ingress:
  - {}
